#!/usr/bin/env bash
# Computes the semantic version and writes _version.py to the repo root.
#
# Version scheme:
#   Major.Minor.Patch — all three components read from the APP_VERSION fallback
#                       line in world_codes.py (single source of truth).
#   Build             — total git commit count (git rev-list --count HEAD); always
#                       the same for a given commit regardless of which workflow
#                       runs this script, so all artefacts from the same commit
#                       share an identical version string.
#                       Requires full history (fetch-depth: 0).
#
# Usage (local):   bash scripts/compute_version.sh
# Usage (CI):      bash scripts/compute_version.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ── Major.Minor.Patch: read from world_codes.py (single source of truth) ──────
WORLD_CODES="$REPO_ROOT/src/traveller_gen/world_codes.py"
VERSION=$(python3 -c "
import re, sys
m = re.search(r'APP_VERSION\s*=\s*\"([0-9]+\.[0-9]+\.[0-9]+)\"', open(sys.argv[1]).read())
print(m.group(1) if m else '0.0.0')
" "$WORLD_CODES")
MAJOR=$(echo "$VERSION" | cut -d. -f1)
MINOR=$(echo "$VERSION" | cut -d. -f2)
PATCH=$(echo "$VERSION" | cut -d. -f3)

# ── Build ─────────────────────────────────────────────────────────────────────
# Total commit count — same for every workflow that checks out the same commit.
# Requires fetch-depth: 0 in CI checkout steps.
BUILD="$(git -C "$REPO_ROOT" rev-list --count HEAD)"

# ── Write _version.py ─────────────────────────────────────────────────────────
VERSION="${MAJOR}.${MINOR}.${PATCH}"
FULL_VERSION="${VERSION}+build.${BUILD}"

cat > "$REPO_ROOT/src/traveller_gen/_version.py" <<EOF
# Auto-generated by scripts/compute_version.sh — do not edit or commit
__version__ = "${FULL_VERSION}"
__version_tuple__ = (${MAJOR}, ${MINOR}, ${PATCH})
__build__ = "${BUILD}"
EOF

echo "Version: $FULL_VERSION"
