#!/usr/bin/env bash
# Computes the semantic version and writes _version.py to the repo root.
#
# Version scheme:
#   Major.Minor — from branch name (v1.5.x → 1.5), fallback to VERSION file
#   Patch       — extracted from APP_VERSION fallback in world_codes.py
#                 (single source of truth for the manually-maintained version)
#   Build       — short git SHA (first 7 chars of HEAD); always the same for a
#                 given commit regardless of which workflow runs this script,
#                 so all built artefacts from the same commit share an identical
#                 version string.  Falls back to "dev" if git is unavailable.
#
# Usage (local):   bash scripts/compute_version.sh
# Usage (CI):      bash scripts/compute_version.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ── Major.Minor ───────────────────────────────────────────────────────────────
BRANCH=$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
if [[ "$BRANCH" =~ ^v([0-9]+)\.([0-9]+) ]]; then
    MAJOR="${BASH_REMATCH[1]}"
    MINOR="${BASH_REMATCH[2]}"
elif [[ -f "$REPO_ROOT/VERSION" ]]; then
    # VERSION file contains "major.minor" — used on main after merge
    IFS='.' read -r MAJOR MINOR _ < "$REPO_ROOT/VERSION"
else
    MAJOR=0; MINOR=0
fi

# ── Patch: read from world_codes.py (single source of truth) ─────────────────
# Extracts the patch digit from the APP_VERSION fallback line, e.g. "1.5.33" → 33
WORLD_CODES="$REPO_ROOT/src/traveller_gen/world_codes.py"
PATCH=$(python3 -c "
import re, sys
m = re.search(r'APP_VERSION\s*=\s*\"[0-9]+\.[0-9]+\.([0-9]+)\"', open(sys.argv[1]).read())
print(m.group(1) if m else '0')
" "$WORLD_CODES")

# ── Build ─────────────────────────────────────────────────────────────────────
# Short git SHA — identical for every build from the same commit.
BUILD="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "dev")"

# ── Write _version.py ─────────────────────────────────────────────────────────
VERSION="${MAJOR}.${MINOR}.${PATCH}"
FULL_VERSION="${VERSION}+build.${BUILD}"

cat > "$REPO_ROOT/src/traveller_gen/_version.py" <<EOF
# Auto-generated by scripts/compute_version.sh — do not edit or commit
__version__ = "${FULL_VERSION}"
__version_tuple__ = (${MAJOR}, ${MINOR}, ${PATCH})
__build__ = "${BUILD}"
EOF

echo "Version: $FULL_VERSION"
