#Requires -Version 5.1
<#
.SYNOPSIS
    Compute the semantic version and write _version.py to the repo root.

.DESCRIPTION
    Version scheme:
      Major.Minor — from branch name (v1.5.x -> 1.5), fallback to VERSION file
      Patch       — count of schema-bump-N tags; falls back to counting
                    schema-touching commits when no tags exist (local dev).
      Build       — first positional argument; defaults to total commit count.

.EXAMPLE
    .\scripts\compute_version.ps1

.EXAMPLE
    .\scripts\compute_version.ps1 321
#>

param([string]$BuildNumber = "")

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot  = Split-Path -Parent $ScriptDir

# ── Major.Minor ───────────────────────────────────────────────────────────────
$Branch = (git -C $RepoRoot rev-parse --abbrev-ref HEAD 2>$null) -replace "`n",""
if ($Branch -match '^v(\d+)\.(\d+)') {
    $Major = $Matches[1]; $Minor = $Matches[2]
} elseif (Test-Path (Join-Path $RepoRoot 'VERSION')) {
    $Parts = ((Get-Content (Join-Path $RepoRoot 'VERSION')) -split '\.')
    $Major = $Parts[0]; $Minor = $Parts[1]
} else {
    $Major = 0; $Minor = 0
}

# ── Patch: schema-bump tags ───────────────────────────────────────────────────
$Tags = git -C $RepoRoot tag -l 'schema-bump-*' 2>$null
$Patch = @($Tags | Where-Object { $_ }).Count
if ($Patch -eq 0) {
    $Commits = git -C $RepoRoot log --oneline HEAD -- traveller_world_schema.json 2>$null
    $Patch = @($Commits | Where-Object { $_ }).Count
}

# ── Build ─────────────────────────────────────────────────────────────────────
if ($BuildNumber -ne "") {
    $Build = $BuildNumber
} else {
    $Build = (git -C $RepoRoot rev-list --count HEAD 2>$null) -replace "`n",""
    if (-not $Build) { $Build = "local" }
}

# ── Write _version.py ─────────────────────────────────────────────────────────
$Version     = "$Major.$Minor.$Patch"
$FullVersion = "${Version}+build.${Build}"

$Content = @"
# Auto-generated by scripts/compute_version.ps1 — do not edit or commit
__version__ = "$FullVersion"
__version_tuple__ = ($Major, $Minor, $Patch)
__build__ = "$Build"
"@

$VersionFile = Join-Path $RepoRoot '_version.py'
[System.IO.File]::WriteAllText($VersionFile, $Content, [System.Text.UTF8Encoding]::new($false))

Write-Host "Version: $FullVersion"
