#!/usr/bin/env bash
# Computes the semantic version and writes _version.py to the repo root.
#
# Version scheme:
#   Major.Minor — from branch name (v1.5.x → 1.5), fallback to VERSION file
#   Patch       — count of commits that touched traveller_world_schema.json
#   Build       — $1 argument (GitHub run_number in CI); "local" when absent
#
# Usage (local):   bash scripts/compute_version.sh
# Usage (CI):      bash scripts/compute_version.sh ${{ github.run_number }}

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ── Major.Minor ───────────────────────────────────────────────────────────────
BRANCH=$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
if [[ "$BRANCH" =~ ^v([0-9]+)\.([0-9]+) ]]; then
    MAJOR="${BASH_REMATCH[1]}"
    MINOR="${BASH_REMATCH[2]}"
elif [[ -f "$REPO_ROOT/VERSION" ]]; then
    # VERSION file contains "major.minor" — used on main after merge
    IFS='.' read -r MAJOR MINOR _ < "$REPO_ROOT/VERSION"
else
    MAJOR=0; MINOR=0
fi

# ── Patch: schema-touching commits ───────────────────────────────────────────
PATCH=$(git -C "$REPO_ROOT" log --oneline HEAD -- traveller_world_schema.json \
        | wc -l | tr -d ' ')

# ── Build ─────────────────────────────────────────────────────────────────────
BUILD="${1:-local}"

# ── Write _version.py ─────────────────────────────────────────────────────────
VERSION="${MAJOR}.${MINOR}.${PATCH}"
FULL_VERSION="${VERSION}+build.${BUILD}"

cat > "$REPO_ROOT/_version.py" <<EOF
# Auto-generated by scripts/compute_version.sh — do not edit or commit
__version__ = "${FULL_VERSION}"
__version_tuple__ = (${MAJOR}, ${MINOR}, ${PATCH})
__build__ = "${BUILD}"
EOF

echo "Version: $FULL_VERSION"
